"""initial

Revision ID: bb61556b3a65
Revises: 
Create Date: 2026-06-09 08:51:43.088585

"""
from alembic import op
import sqlalchemy as sa


revision = 'bb61556b3a65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
